// ngtlicense - command line front end to the NextGen Tweaks licensing core.
//
// This is the ground-truth tool: it can do everything the Discord bot does
// (keygen, issue, revoke, info) plus the account / validation flows the server
// exposes, all against the same libnglicense core and database. It exists so
// the licensing system is fully usable and testable on its own.
//
//   ngtlicense keygen                         create the issuer key pair
//   ngtlicense issue --duration 30d           mint a 30-day licence
//   ngtlicense issue --uses 25                mint a 25-use licence
//   ngtlicense info <keyId|key>               show a licence's state
//   ngtlicense revoke <keyId>                 revoke a licence
//   ngtlicense verify <key>                   offline signature check only
//   ngtlicense create-account <user> <pass> <key>
//   ngtlicense signin <user> <pass> [key]
//   ngtlicense pubkey-header                  emit the C++ header for the app
//
// Paths default to ./data next to the executable; override with NGT_DATA_DIR.
#include "nglicense/Crypto.h"
#include "nglicense/License.h"
#include "nglicense/LicenseService.h"

#include <array>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

using namespace ngl;

namespace {

std::string dataDir()
{
    if (const char *env = std::getenv("NGT_DATA_DIR"))
        return env;
    return "data";
}

std::string keyPath() { return dataDir() + "/issuer_key.bin"; }
std::string pubPath() { return dataDir() + "/issuer_public.bin"; }
std::string dbPath() { return dataDir() + "/licenses.db"; }

bool writeFile(const std::string &path, const Bytes &data)
{
    std::ofstream out(path, std::ios::binary);
    if (!out)
        return false;
    out.write(reinterpret_cast<const char *>(data.data()), static_cast<std::streamsize>(data.size()));
    return out.good();
}

Bytes readFile(const std::string &path)
{
    std::ifstream in(path, std::ios::binary);
    if (!in)
        return {};
    return Bytes((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
}

std::optional<std::array<std::uint8_t, 32>> loadPublicKey()
{
    Bytes raw = readFile(pubPath());
    if (raw.size() != 32)
        return std::nullopt;
    std::array<std::uint8_t, 32> key{};
    std::copy(raw.begin(), raw.end(), key.begin());
    return key;
}

std::optional<std::array<std::uint8_t, 32>> loadSeed()
{
    Bytes raw = readFile(keyPath());
    if (raw.size() != 32)
        return std::nullopt;
    std::array<std::uint8_t, 32> seed{};
    std::copy(raw.begin(), raw.end(), seed.begin());
    return seed;
}

std::string argValue(const std::vector<std::string> &args, const std::string &flag)
{
    for (std::size_t i = 0; i + 1 < args.size(); ++i) {
        if (args[i] == flag)
            return args[i + 1];
    }
    return {};
}

std::string formatTime(std::int64_t unix)
{
    if (unix == 0)
        return "-";
    std::time_t t = static_cast<std::time_t>(unix);
    char buffer[32];
    std::strftime(buffer, sizeof(buffer), "%Y-%m-%d %H:%M", std::localtime(&t));
    return buffer;
}

int cmdKeygen()
{
    if (readFile(keyPath()).size() == 32) {
        std::cerr << "An issuer key already exists at " << keyPath()
                  << ".\nDelete it only if you intend to invalidate every key you have issued.\n";
        return 1;
    }

    KeyPair pair = crypto::generateKeyPair();
    if (!writeFile(keyPath(), Bytes(pair.privateSeed.begin(), pair.privateSeed.end()))
        || !writeFile(pubPath(), Bytes(pair.publicKey.begin(), pair.publicKey.end()))) {
        std::cerr << "Could not write the key files. Does " << dataDir() << " exist?\n";
        return 1;
    }

    std::cout << "Issuer key pair created.\n"
              << "  private seed : " << keyPath() << "   (KEEP SECRET - bot/server only)\n"
              << "  public key   : " << pubPath() << "\n\n"
              << "Embed the public key in the desktop app with:\n"
              << "  ngtlicense pubkey-header\n";
    return 0;
}

int cmdPubkeyHeader()
{
    auto pub = loadPublicKey();
    if (!pub) {
        std::cerr << "No public key found. Run 'ngtlicense keygen' first.\n";
        return 1;
    }

    std::cout << "// Generated by 'ngtlicense pubkey-header'. Paste into the desktop app.\n"
              << "// This is the PUBLIC half of your issuer key - safe to ship.\n"
              << "#pragma once\n#include <array>\n#include <cstdint>\n\n"
              << "inline constexpr std::array<std::uint8_t, 32> kNextGenLicensePublicKey = {\n    ";
    for (std::size_t i = 0; i < pub->size(); ++i) {
        std::printf("0x%02X", (*pub)[i]);
        if (i + 1 < pub->size())
            std::cout << ", ";
        if ((i + 1) % 8 == 0 && i + 1 < pub->size())
            std::cout << "\n    ";
    }
    std::cout << "\n};\n";
    return 0;
}

int cmdIssue(const std::vector<std::string> &args)
{
    auto seed = loadSeed();
    auto pub = loadPublicKey();
    if (!seed || !pub) {
        std::cerr << "No issuer key. Run 'ngtlicense keygen' first.\n";
        return 1;
    }

    IssueSpec spec;
    const std::string duration = argValue(args, "--duration");
    const std::string uses = argValue(args, "--uses");
    spec.notes = argValue(args, "--note");
    spec.discordUserId = argValue(args, "--discord");
    spec.issuedBy = "cli";

    if (!duration.empty()) {
        auto seconds = parseDuration(duration);
        if (!seconds) {
            std::cerr << "Bad duration '" << duration << "'. Use e.g. 30d, 12h, 1y.\n";
            return 1;
        }
        spec.type = LicenseType::Duration;
        spec.durationSeconds = *seconds;
    } else if (!uses.empty()) {
        spec.type = LicenseType::Uses;
        spec.maxUses = static_cast<std::uint32_t>(std::strtoul(uses.c_str(), nullptr, 10));
    } else if (std::find(args.begin(), args.end(), "--lifetime") != args.end()) {
        spec.type = LicenseType::Lifetime;
    } else {
        std::cerr << "Specify --duration <e.g.30d>, --uses <n>, or --lifetime.\n";
        return 1;
    }

    Database db;
    std::string error;
    if (!db.open(dbPath(), &error)) {
        std::cerr << "Database error: " << error << "\n";
        return 1;
    }

    LicenseService service(db, *pub);
    service.setIssuerSeed(*seed);

    IssueResult result = service.issue(spec);
    if (!result.ok) {
        std::cerr << result.message << "\n";
        return 1;
    }

    std::cout << "Licence issued (" << toString(spec.type) << ")\n"
              << "  key id : " << result.keyId << "\n\n"
              << result.keyString << "\n";
    return 0;
}

int cmdInfo(const std::vector<std::string> &args)
{
    if (args.empty()) {
        std::cerr << "Usage: ngtlicense info <keyId|key>\n";
        return 1;
    }
    auto pub = loadPublicKey();
    if (!pub) {
        std::cerr << "No public key. Run 'ngtlicense keygen' first.\n";
        return 1;
    }

    // Accept either a raw key id or a full key string.
    std::string keyId = args[0];
    if (auto parsed = license::parse(args[0]))
        keyId = parsed->payload.keyIdHex();

    Database db;
    std::string error;
    if (!db.open(dbPath(), &error)) {
        std::cerr << "Database error: " << error << "\n";
        return 1;
    }

    LicenseService service(db, *pub);
    LicenseInfo info = service.lookup(keyId);
    if (!info.exists) {
        std::cerr << "No licence with id " << keyId << "\n";
        return 1;
    }

    std::cout << "Licence " << info.keyId << "\n"
              << "  type      : " << toString(info.type) << "\n"
              << "  status    : " << (info.revoked ? "REVOKED" : "active") << "\n"
              << "  issued    : " << formatTime(info.issuedUnix) << "\n";
    if (info.type == LicenseType::Duration)
        std::cout << "  expires   : " << formatTime(info.expiryUnix) << "\n";
    if (info.type == LicenseType::Uses)
        std::cout << "  uses      : " << info.usesConsumed << " / " << info.maxUses << "\n";
    std::cout << "  bound to  : "
              << (info.boundAccountId ? ("account " + std::to_string(*info.boundAccountId))
                                      : std::string("(unbound)"))
              << "\n";
    if (!info.discordUserId.empty())
        std::cout << "  discord   : " << info.discordUserId << "\n";
    if (!info.notes.empty())
        std::cout << "  note      : " << info.notes << "\n";
    return 0;
}

int cmdRevoke(const std::vector<std::string> &args)
{
    if (args.empty()) {
        std::cerr << "Usage: ngtlicense revoke <keyId>\n";
        return 1;
    }
    auto pub = loadPublicKey();
    if (!pub)
        return 1;

    Database db;
    std::string error;
    if (!db.open(dbPath(), &error)) {
        std::cerr << "Database error: " << error << "\n";
        return 1;
    }
    LicenseService service(db, *pub);
    if (!service.revoke(args[0], &error)) {
        std::cerr << "Could not revoke " << args[0]
                  << (error.empty() ? " (no such licence)" : ": " + error) << "\n";
        return 1;
    }
    std::cout << "Licence " << args[0] << " revoked.\n";
    return 0;
}

int cmdVerify(const std::vector<std::string> &args)
{
    if (args.empty()) {
        std::cerr << "Usage: ngtlicense verify <key>\n";
        return 1;
    }
    auto pub = loadPublicKey();
    if (!pub)
        return 1;

    auto parsed = license::parseAndVerify(*pub, args[0]);
    if (!parsed) {
        std::cout << "INVALID - signature does not match (forged or corrupt).\n";
        return 1;
    }
    std::cout << "GENUINE - signed by this issuer.\n"
              << "  key id : " << parsed->payload.keyIdHex() << "\n"
              << "  type   : " << toString(parsed->payload.type) << "\n";
    return 0;
}

int cmdCreateAccount(const std::vector<std::string> &args)
{
    if (args.size() < 3) {
        std::cerr << "Usage: ngtlicense create-account <username> <password> <key>\n";
        return 1;
    }
    auto pub = loadPublicKey();
    if (!pub)
        return 1;

    Database db;
    std::string error;
    if (!db.open(dbPath(), &error)) {
        std::cerr << "Database error: " << error << "\n";
        return 1;
    }
    LicenseService service(db, *pub);
    ValidationResult r = service.createAccount(args[0], "", args[1], args[2], "cli-machine");
    std::cout << (r.ok ? "OK: " : "FAILED: ") << r.reason << "\n";
    return r.ok ? 0 : 1;
}

int cmdSignIn(const std::vector<std::string> &args)
{
    if (args.size() < 2) {
        std::cerr << "Usage: ngtlicense signin <username> <password> [key]\n";
        return 1;
    }
    auto pub = loadPublicKey();
    if (!pub)
        return 1;

    Database db;
    std::string error;
    if (!db.open(dbPath(), &error)) {
        std::cerr << "Database error: " << error << "\n";
        return 1;
    }
    LicenseService service(db, *pub);
    const std::string key = args.size() >= 3 ? args[2] : std::string();
    ValidationResult r = service.signIn(args[0], args[1], key, "cli-machine", /*consumeUse=*/true);
    std::cout << (r.ok ? "OK: " : "FAILED: ") << r.reason << "\n";
    if (r.ok) {
        if (r.expiryUnix > 0)
            std::cout << "  expires: " << formatTime(r.expiryUnix) << "\n";
        if (r.usesRemaining >= 0)
            std::cout << "  uses left: " << r.usesRemaining << "\n";
    }
    return r.ok ? 0 : 1;
}

int cmdList(const std::vector<std::string> &args)
{
    auto pub = loadPublicKey();
    if (!pub) {
        std::cerr << "No public key. Run 'ngtlicense keygen' first.\n";
        return 1;
    }
    Database db;
    std::string error;
    if (!db.open(dbPath(), &error)) {
        std::cerr << "Database error: " << error << "\n";
        return 1;
    }
    LicenseService service(db, *pub);
    const std::string forUser = args.empty() ? std::string() : args[0];
    const std::vector<LicenseInfo> licences = service.listLicenses(forUser, 50);
    if (licences.empty()) {
        std::cout << "No licences.\n";
        return 0;
    }
    for (const LicenseInfo &info : licences) {
        std::cout << info.keyId << "  " << toString(info.type);
        if (info.revoked)
            std::cout << "  REVOKED";
        else if (info.type == LicenseType::Uses)
            std::cout << "  " << info.usesConsumed << "/" << info.maxUses;
        else if (info.type == LicenseType::Duration)
            std::cout << "  expires " << formatTime(info.expiryUnix);
        std::cout << (info.boundAccountId ? "  [bound]" : "  [unbound]");
        if (!info.notes.empty())
            std::cout << "  \"" << info.notes << "\"";
        std::cout << "\n";
    }
    return 0;
}

void printUsage()
{
    std::cout << "ngtlicense - NextGen Tweaks licensing\n\n"
              << "  keygen                              create the issuer key pair\n"
              << "  pubkey-header                       emit the C++ public-key header\n"
              << "  issue --duration 30d [--note ..]    mint a time-limited licence\n"
              << "  issue --uses 25                     mint a use-limited licence\n"
              << "  issue --lifetime                    mint an unlimited licence\n"
              << "  info <keyId|key>                    show a licence\n"
              << "  revoke <keyId>                      revoke a licence\n"
              << "  verify <key>                        offline signature check\n"
              << "  create-account <user> <pass> <key>  register + activate\n"
              << "  signin <user> <pass> [key]          authenticate + validate\n";
}

} // namespace

int main(int argc, char **argv)
{
    std::vector<std::string> args(argv + 1, argv + argc);
    if (args.empty()) {
        printUsage();
        return 1;
    }

    const std::string command = args[0];
    const std::vector<std::string> rest(args.begin() + 1, args.end());

    try {
        if (command == "keygen")
            return cmdKeygen();
        if (command == "pubkey-header")
            return cmdPubkeyHeader();
        if (command == "issue")
            return cmdIssue(rest);
        if (command == "info")
            return cmdInfo(rest);
        if (command == "list")
            return cmdList(rest);
        if (command == "revoke")
            return cmdRevoke(rest);
        if (command == "verify")
            return cmdVerify(rest);
        if (command == "create-account")
            return cmdCreateAccount(rest);
        if (command == "signin")
            return cmdSignIn(rest);
    } catch (const std::exception &ex) {
        std::cerr << "Error: " << ex.what() << "\n";
        return 1;
    }

    printUsage();
    return 1;
}
